name:                fwp
version:             0.1.0.0
github:              "snowmang1/fwp"
license:             BSD-3-Clause
author:              "Evan Drake"
maintainer:          "evanmdrake@icloud.com"
copyright:           "Evan Drake"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            AI

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/snowmang1/Fast-Weight-Programmer#readme>

dependencies:
- base >= 4.7 && < 5
- tasty >= 1.4
- tasty-hunit >= 0.10
- matrix >= 0.3.6

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  fwp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fwp

tests:
  fwp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fwp
