name: Haskell CI

on:
  push:
    branches: ["THE-61"]
  pull_request:
    branches: ["trunk"]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Stack setup
        run: stack upgrade
      - name: Test
        run: stack test
