name: Haskell CI

on:
  push:
    branches: ["THE-61"]
  pull_request:
    branches: ["trunk"]

  jobs:
    build:

      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - name: Stack setup
          # run: sudo apt-get install g++ gcc libc6-dev libffi-dev libgmp-dev make xz-utils zlib1g-dev git gnupg netbase
          run: curl -sSL https://get.haskellstack.org/ | sh

        - name: Test
          run: stack test
